backend:
  name: github
  branch: master
  repo: Moskowitza/VeganWitWiz

media_folder: src/images
public_folder: /images
collections:
  - name: "team"
    label: "Team"
    folder: "src/team"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Team Member", name: "title", widget: "string" }
      - { label: "Bio", name: "bio", widget: "markdown" }
  - name: "posts"
    label: "Posts"
    description: "Blog Posts, tell me about the cheese steak"
    folder: "src/posts"
    create: true
    delete: false
    extension: "md"
    format: "frontmatter"
    frontmatter_delimiter: ["---", "---"]
    slug: "{{slug}}"
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Hero Image", name: "hero", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
